apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: paperless-ocr-autoscale
  labels:
    io.kompose.service: paperless-ocr
  namespace: paperless
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paperless-ocr
  targetCPUUtilizationPercentage: 40